### ISSUE TITLE
Enhancement - if no openapi key - fall back to local gpt-j instance / 2.7B would be fine.

### ISSUE THREAD

**Issue by johndpope** [robgon-art/ai-tunes#2]
I can't access openai / no api key 

I did some digging and found this code that uses gpt-j 
https://github.com/kingoflolz/mesh-transformer-jax/#gpt-j-6b

```python

def gpt3_respond(self, question):
		prepend = self.stem + "\n".join(self.messagecache)

		prompt = f"{prepend}\nQ: \"{question}\"\nA: \""

		response = openai.Completion.create(
			engine="davinci", 
			prompt=prompt, 
			max_tokens=80, 
			temperature=0.75, 
			stop="\"",
			frequency_penalty=0.5,
			)

		response_text = response["choices"][0]["text"]

		self.messagecache.append(f"Interviewer: \"{question}\"\n{self.name}: \"{response_text}\"\n")
		self.messagelog.append(f"Interviewer: \"{question}\"\n{self.name}: \"{response_text}\"\n")

		self.messagecache = self.messagecache[::-1][0:self.messagecachelen]

		return response_text

	def gptj_respond(self, question):

		prepend = self.stem + "\n".join(self.messagecache)

		prompt = f"{prepend}\nQ: \"{question}\"\nA: \""

		query = SimpleCompletion(
			prompt, 
			length=75, 
			t=0.78, 
			)

		response_text = query.simple_completion().split("\"")[0]

		self.messagecache.append(f"Interviewer: \"{question}\"\n{self.name}: \"{response_text}\"\n")
		self.messagelog.append(f"Interviewer: \"{question}\"\n{self.name}: \"{response_text}\"\n")

		self.messagecache = self.messagecache[::-1][0:self.messagecachelen]

		return response_text


```

https://github.com/CthulhuOnIce/OpenLFA/blob/4441eb9a4bdc0ffbc894e2a2967575981255442d/learnfromanyone.py#L47

There's also this code

https://github.com/sylinrl/TruthfulQA/blob/171ce46f303f8919aef14a490eeb9b1594df2a3d/truthfulqa/models.py

**Comment by johndpope** [comment]
example of gtp-j with colab 
https://colab.research.google.com/github/kingoflolz/mesh-transformer-jax/blob/master/colab_demo.ipynb

**Comment by robgon-art** [comment]
Ok, thanks. I'll check that out.

**Comment by robgon-art** [comment]
Hello,

I experimented with GPT-J for doing the first part of AI-Tunes, creating a band name and song title. 

It works and it's quite good!

Here's the prompt:
```
Create a new song title a new band name. Be creative!
###
Band name: The Execs
Song title: Company Meeting
###
Band name: The One Chords
Song title: Moving Down to Burlington
###
Band name
```

And here are the results:
```
Band name: The Spinning Circles
Song title: Scandal
###
Band name: The Mouth Breathers
Song title: Fight to Survive
###
Band name: Crying Cribs
Song title: Can't Get Used to Losing You
###
Band name: Hotline Bling
Song title: Free Fire
###
Band name: The Rock Band
Song title: Up the Revolution
###
```
I created a Colab here: https://colab.research.google.com/github/robgon-art/ai-tunes/blob/main/Using_GPT_J_to_Create_a_Band_Name_and_Song_Title.ipynb

The next step, generating the music, is a bit more involved as I have to fine-tune GPT-J. I'll keep you posted...

**Comment by johndpope** [comment]
found this - https://gist.github.com/kinoc/2d636a68876cd3de7b6e9c9452b61089

UPDATE
fine tuning + deepspeed
https://gist.github.com/kinoc/dca36b12b5e956688a9b92a87ba7c52c
